version: '3.8'

services:

  backend:
    build: ./backend
    networks:
      cpinet:
        ipv4_address: 172.16.1.2
    environment:
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    ports: 
      - 5001:5001

  frontend:
    build: ./frontend
    networks:
      cpinet:
        ipv4_address: 172.16.1.3
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8081:8081

networks:
  cpinet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.1.0/29
